version: "3.6"

services:
  app:
    build: .
    depends_on:
      - db
    env_file:
      - ./bot/.bot.env
      - ./bot/.db.env
    networks:
      - default
    volumes:
      - .:/app
    restart: always

  db:
    env_file:
      - ./bot/.db.env
    image: postgres:14.4-alpine
    networks:
      - default
    ports:
      - 5455:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
